      SUBROUTINE URDFIL(LSTOP,LOVRWRT,KSTEP,KINC,DTIME,TIME)
C
      INCLUDE 'ABA_PARAM.INC'
C
      DIMENSION ARRAY(513),JRRAY(NPRECD,513),TIME(2)
      EQUIVALENCE (ARRAY(1),JRRAY(1,1))
      PARAMETER(DEEL=3.0D1)

      LOVRWRT=1
C
C FIND CURRENT INCREMENT.
C
      CALL POSFIL(KSTEP,KINC,ARRAY,JRCD)
      DO K1=1,999999
         CALL DBFILE(0,ARRAY,JRCD)
         IF (JRCD .NE. 0) GO TO 110
         KEY=JRRAY(1,2)

C
C RECORD 12 CONTAINS VALUES FOR SINV
C
         IF (KEY.EQ.101) THEN
            U1=ARRAY(4)
            U2=ARRAY(5)
            U3=ARRAY(6)
            IF (SQRT(U1*U1+U2*U2) .GT. DEEL) THEN
               LSTOP=1
               GOTO 110
            END IF
         END IF
      END DO
 110  CONTINUE

      RETURN
      END SUBROUTINE